package hb

import "errors"

type flags []string

var profiles = map[string]flags{
    "mkv_h265_1080p30": {
        "-Z", "Matroska/H.265 MKV 1080p30",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_h265_2160p60_surround": {
        "-Z", "General/Super HQ 2160p60 4K HEVC Surround",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_h265_2160p60_no_audio": {
        "-Z", "General/Super HQ 2160p60 4K HEVC Surround",
        "--audio", "none",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_h265_1080p30_no_sound": {
        "-Z", "Matroska/H.265 MKV 1080p30",
        "--audio", "none",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_h265_2160p60_fast": {
        "-Z", "General/Fast 2160p60 4K HEVC",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_h265_2160p60_very_fast": {
        "-Z", "General/Very Fast 2160p60 4K HEVC",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_h265_2060p60_4k": {
        "-Z", "Matroska/H.265 MKV 2160p60 4K",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_h265_2060p60_4k_28.0": {
        "-Z", "Matroska/H.265 MKV 2160p60 4K",
        "-q", "28.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_h265_2060p60_4k_18.0": {
        "-Z", "Matroska/H.265 MKV 2160p60 4K",
        "-q", "18.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_h265_2060p60_4k_19.0": {
        "-Z", "Matroska/H.265 MKV 2160p60 4K",
        "-q", "19.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_h265_2060p60_4k_20.0": {
        "-Z", "Matroska/H.265 MKV 2160p60 4K",
        "-q", "20.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    // MKV 2160 q18-28
    "mkv_2160_q18": {
        "-Z", "Matroska/H.265 MKV 2160p60 4K",
        "-q", "18.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_2160_q19": {
        "-Z", "Matroska/H.265 MKV 2160p60 4K",
        "-q", "19.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_2160_q20": {
        "-Z", "Matroska/H.265 MKV 2160p60 4K",
        "-q", "20.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_2160_q21": {
        "-Z", "Matroska/H.265 MKV 2160p60 4K",
        "-q", "21.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_2160_q22": {
        "-Z", "Matroska/H.265 MKV 2160p60 4K",
        "-q", "22.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_2160_q23": {
        "-Z", "Matroska/H.265 MKV 2160p60 4K",
        "-q", "23.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_2160_q24": {
        "-Z", "Matroska/H.265 MKV 2160p60 4K",
        "-q", "24.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_2160_q25": {
        "-Z", "Matroska/H.265 MKV 2160p60 4K",
        "-q", "25.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_2160_q26": {
        "-Z", "Matroska/H.265 MKV 2160p60 4K",
        "-q", "26.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_2160_q27": {
        "-Z", "Matroska/H.265 MKV 2160p60 4K",
        "-q", "27.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_2160_q28": {
        "-Z", "Matroska/H.265 MKV 2160p60 4K",
        "-q", "28.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },

    // MKV 1080 q18-28
    "mkv_1080_q18": {
        "-Z", "Matroska/H.265 MKV 1080p30",
        "-q", "18.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_1080_q19": {
        "-Z", "Matroska/H.265 MKV 1080p30",
        "-q", "19.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_1080_q20": {
        "-Z", "Matroska/H.265 MKV 1080p30",
        "-q", "20.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_1080_q21": {
        "-Z", "Matroska/H.265 MKV 1080p30",
        "-q", "21.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_1080_q22": {
        "-Z", "Matroska/H.265 MKV 1080p30",
        "-q", "22.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_1080_q23": {
        "-Z", "Matroska/H.265 MKV 1080p30",
        "-q", "23.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_1080_q24": {
        "-Z", "Matroska/H.265 MKV 1080p30",
        "-q", "24.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_1080_q25": {
        "-Z", "Matroska/H.265 MKV 1080p30",
        "-q", "25.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_1080_q26": {
        "-Z", "Matroska/H.265 MKV 1080p30",
        "-q", "26.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_1080_q27": {
        "-Z", "Matroska/H.265 MKV 1080p30",
        "-q", "27.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_1080_q28": {
        "-Z", "Matroska/H.265 MKV 1080p30",
        "-q", "28.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },

    // MKV 576 q18-28
    "mkv_576_q18": {
        "-Z", "Matroska/H.265 MKV 576p25",
        "-q", "18.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_576_q19": {
        "-Z", "Matroska/H.265 MKV 576p25",
        "-q", "19.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_576_q20": {
        "-Z", "Matroska/H.265 MKV 576p25",
        "-q", "20.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_576_q21": {
        "-Z", "Matroska/H.265 MKV 576p25",
        "-q", "21.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_576_q22": {
        "-Z", "Matroska/H.265 MKV 576p25",
        "-q", "22.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_576_q23": {
        "-Z", "Matroska/H.265 MKV 576p25",
        "-q", "23.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_576_q24": {
        "-Z", "Matroska/H.265 MKV 576p25",
        "-q", "24.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_576_q25": {
        "-Z", "Matroska/H.265 MKV 576p25",
        "-q", "25.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_576_q26": {
        "-Z", "Matroska/H.265 MKV 576p25",
        "-q", "26.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_576_q27": {
        "-Z", "Matroska/H.265 MKV 576p25",
        "-q", "27.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_576_q28": {
        "-Z", "Matroska/H.265 MKV 576p25",
        "-q", "28.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },

    // MKV 480 q18-28
    "mkv_480_q18": {
        "-Z", "Matroska/H.265 MKV 480p30",
        "-q", "18.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_480_q19": {
        "-Z", "Matroska/H.265 MKV 480p30",
        "-q", "19.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_480_q20": {
        "-Z", "Matroska/H.265 MKV 480p30",
        "-q", "20.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_480_q21": {
        "-Z", "Matroska/H.265 MKV 480p30",
        "-q", "21.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_480_q22": {
        "-Z", "Matroska/H.265 MKV 480p30",
        "-q", "22.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_480_q23": {
        "-Z", "Matroska/H.265 MKV 480p30",
        "-q", "23.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_480_q24": {
        "-Z", "Matroska/H.265 MKV 480p30",
        "-q", "24.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_480_q25": {
        "-Z", "Matroska/H.265 MKV 480p30",
        "-q", "25.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_480_q26": {
        "-Z", "Matroska/H.265 MKV 480p30",
        "-q", "26.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_480_q27": {
        "-Z", "Matroska/H.265 MKV 480p30",
        "-q", "27.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
    "mkv_480_q28": {
        "-Z", "Matroska/H.265 MKV 480p30",
        "-q", "28.0",
        "--all-audio",
        "--non-anamorphic",
        "--all-subtitles",
        "--subtitle-burned=none",
    },
}

var (
    ProfileNotFoundErr = errors.New("Profile not found")
    InvalidInPathErr = errors.New("Invalid inPath")
    InvalidOutPathErr = errors.New("Invalid outPath")
)

func getFlags(profile, inPath, outPath string) (flags, error) {
    profileFlags, found := profiles[profile]
    if !found {
        return nil, ProfileNotFoundErr
    }
    if len(inPath) == 0 {
        return nil, InvalidInPathErr
    }
    if len(outPath) == 0 {
        return nil, InvalidOutPathErr
    }
    standardFlags := []string{
        "-i", inPath,
        "-o", outPath,
        "--json",
    }
    combinedFlags := append(standardFlags, profileFlags...)
    return combinedFlags, nil
}
