name: video-tool-box-tcserver
services:
  server:
    container_name: server
    image: "krelinga/video-tool-box-tcserver:buildx-latest"
    ports:
      - "25000:25000"
    volumes:
      - type: volume
        source: videos
        target: /videos
      - type: volume
        source: videos
        target: /nas/media
      - state:/state
    environment:
      VTB_TCSERVER_STATE_PATH: /state/state
      # This is tuned for my gaming PC.  18 cores available for work, 3 cores
      # per-file = 6 workers.
      VTB_TCSERVER_FILE_WORKERS: 6
      VTB_TCSERVER_SHOW_WORKERS: 2
      VTB_TCSERVER_SPREAD_WORKERS: 2
    restart: unless-stopped

volumes:
  videos:
    driver: local
    driver_opts:
      type: cifs
      device: //truenas.i.krel.ing/media
      o: "addr=truenas.i.krel.ing,username=${SMB_USER},password=${SMB_PASSWORD},file_mode=0666,dir_mode=0777"
  state: {}

